### ISSUE TITLE
Add dark mode icon in the notifications area

### ISSUE THREAD

**Issue by RedEdge967** [PiyushSuthar/Windows-11-Web#16]
Can you add the dark mode toggle to the notifications area? then it will look exactly like the windows 11 operating system. Because the dark mode toggle is in the taskbar, it looks different from the windows 11.
If you can, can you add toggle to the notifications area.

can you add it to here. (see the screenshot below)
![Capture68](https://user-images.githubusercontent.com/91379432/153845926-0a9119f9-9dac-495b-a021-e2a9daf2b531.PNG)

**Comment by PiyushSuthar** [comment]
Actually had added that theme switcher over there just for convenience. I don't have any plans on working on this project any time soon.

**Comment by RedEdge967** [comment]
okay then, you can close this issue
