### ISSUE TITLE
Plz change the look of when you right click

### ISSUE THREAD

**Issue by ask-arim** [PiyushSuthar/Windows-11-Web#19]
Please make the look of a right click look the same as the actual Windows 11.
![Actual Windows 11](https://user-images.githubusercontent.com/111149452/203636474-91591c61-29a5-495c-af0b-f53c174ccf82.png)

**Comment by PiyushSuthar** [comment]
Not having enough time to work on this project for now. If you wish to contribute, you're welcome.

**Comment by ask-arim** [comment]
ok
