### ISSUE TITLE
start menu close on click outside

### ISSUE THREAD

**Issue by Deep-Codes** [PiyushSuthar/Windows-11-Web#4]
There's no way to close the Start Menu currently
Would be a great UX to have it closed on clicking outside

I have implemented a fix for that. Let me know

![win11](https://user-images.githubusercontent.com/61158210/123544702-1bf1b100-d772-11eb-95d5-d8966c4e217b.gif)

Making a PR if needed

**Comment by PiyushSuthar** [comment]
Yeah! I'll really appreciate it if you make a PR! 😊
